import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "(App Name) is at the forefront of AI-driven e-commerce innovation. Our mission is to revolutionize online shopping by integrating advanced technology like 3D product visualization, AI-powered recommendations, and augmented reality.\n\nWhat Sets Us Apart?\n• AI Precision: Tailored suggestions based on your unique preferences and measurements.\n• Interactive Shopping: Engage with realistic 3D models and virtual dressing rooms.\n• Real-Time Experience: Always accurate, always live—stay informed with real-time product updates.\n\nOur Vision:\u2028We believe in blending technology with user-centric design to create intuitive, immersive shopping experiences that are enjoyable and effective.\nJoin Us on this journey to redefine the future of e-commerce!":
              "(App Name) is at the forefront of AI-driven e-commerce innovation. Our mission is to revolutionize online shopping by integrating advanced technology like 3D product visualization, AI-powered recommendations, and augmented reality.\n\nWhat Sets Us Apart?\n• AI Precision: Tailored suggestions based on your unique preferences and measurements.\n• Interactive Shopping: Engage with realistic 3D models and virtual dressing rooms.\n• Real-Time Experience: Always accurate, always live—stay informed with real-time product updates.\n\nOur Vision:\u2028We believe in blending technology with user-centric design to create intuitive, immersive shopping experiences that are enjoyable and effective.\nJoin Us on this journey to redefine the future of e-commerce!",
          'About Us': 'About Us',
          'Privacy Policy': 'Privacy Policy',
          'Terms and conditions': 'Terms and conditions',
          'Continue': 'Continue',
          'Save Changes': 'Save Changes',
          'Account Settings': 'Account Settings',
          'Save': 'Save',
          'Settings': 'Settings',
          'Oliver': 'Oliver',
          'Nike': 'Nike',
          'Notifications': 'Notifications',
          'Reset Password': 'Reset Password',
          'Please replace the respective Widget here':
              'Please replace the respective Widget here',
          'Sound': 'Sound',
          'More': 'More',
          'Remove': 'Remove',
          'Items': 'Items',
          'Logout': 'Logout',
          'Your Style Favorites in One Place':
              'Your Style Favorites in One Place',
          'Air Force 1 Jester XX Black Sonic':
              'Air Force 1 Jester XX Black Sonic',
          'Air Force 1 Shadow Beige Pale Ivory':
              'Air Force 1 Shadow Beige Pale Ivory',
          'Upcoming Party': 'Upcoming Party',
          '121 items': '121 items',
          'Choose an Option': 'Choose an Option',
          'Tour to Dubai': 'Tour to Dubai',
          'Add a profile': 'Add a profile',
          'Language': 'Language',
          'Select Language': 'Select Language',
          'Profile Options': 'Profile Options',
          'Choose a profile to continue': 'Choose a profile to continue',
          'Nike -098': 'Nike -098',
          'Sunglasses': 'Sunglasses',
          'Style & Try-On': 'Style & Try-On',
          'Men': 'Men',
          'Women': 'Women',
          'Kids': 'Kids',
          'Add to Favourites': 'Add to Favourites',
          '\$85.5': '\$85.5',
          '\$96': '\$96',
          '\$115': '\$115',
          'Home': 'Home',
          'Shoes': 'Shoes',
          '25 products found': '25 products found',
          'Search': 'Search',
          'Search product': 'Search product',
          'Favourites': 'Favourites',
          'Profile': 'Profile',
          'Measure': 'Measure',
          'Theme': 'Theme',
          'Emotes': 'Emotes',
          'Mode': 'Mode',
          'AR': 'AR',
          'Resend': 'Resend',
          'Verify': 'Verify',
          'Analyzing': 'Analyzing',
          'Analyzed': 'Analyzed',
          'English (United Kingdom)': 'English (United Kingdom)',
          'English (United States)': 'English (United States)',
          'Hindi': 'Hindi',
          'Spanish': 'Spanish',
          'French': 'French',
          'Name': 'Name',
          'Gender': 'Gender',
          'Weight': 'Weight',
          'Body Type': 'Body Type',
          'Age': 'Age',
          'Measurements': 'Measurements',
          'Height': 'Height',
          'Chest': 'Chest',
          'Bicep': 'Bicep',
          'Waist': 'Waist',
          'Hip': 'Hip',
          '170.00 cm': '170.00 cm',
          '96.00 cm': '96.00 cm',
          '33.00 cm': '33.00 cm',
          '99.00 cm': '99.00 cm',
          'Review Your Measured Data': 'Review Your Measured Data',
          'Verification': 'Verification',
          'Next': 'Next',
          'Account Recovery': 'Account Recovery',
          'Phone / Email': 'Phone / Email',
          'Send code via oli***r@gmail.com': 'Send code via oli***r@gmail.com',
          'Send code via +966 5* **** ***': 'Send code via +966 5* **** ***',
          'Set New Password': 'Set New Password',
          'oliver@gmail.com': 'oliver@gmail.com',
          'New Email': 'New Email',
          'New Number': 'New Number',
          'New Password': 'New Password',
          'Old Password': 'Old Password',
          'Oliver Wyman': 'Oliver Wyman',
          'Confirm New Password': 'Confirm New Password',
          'Confirm Password': 'Confirm Password',
          'Confirm New Email': 'Confirm New Email',
          'Confirm New Number': 'Confirm New Number',
          'Update your email address.': 'Update your email address.',
          'Update your phone number.': 'Update your phone number.',
          'Update Your Profile Information': 'Update Your Profile Information',
          'Edit Profile': 'Edit Profile',
          'Title': 'Title',
          'Submit': 'Submit',
          'Help': 'Help',
          'Cap': 'Cap',
          'Buy': 'Buy',
          'Explain the problem': 'Explain the problem',
          'Login to explore AI styling.': 'Login to explore AI styling.',
          'Add your query here': 'Add your query here',
          'How It Works': 'How It Works',
          'Password': 'Password',
          'Log in': 'Log in',
          'Email': 'Email',
          'Phone': 'Phone',
          'Create Profile': 'Create Profile',
          'Set Up Your Profile': 'Set Up Your Profile',
          'Enter details for personalized picks':
              'Enter details for personalized picks',
          'Success': 'Success',
          'By continuing you accept our': 'By continuing you accept our',
          'Register to start your personalized shopping journey':
              'Register to start your personalized shopping journey',
          'Congratulations! Password has been successfully updated':
              'Congratulations! Password has been successfully updated',
          'Congratulations! You has been \nsuccessfully created':
              'Congratulations! You has been \nsuccessfully created',
          'Congratulations! Your profile has been successfully created':
              'Congratulations! Your profile has been successfully created',
          'Congratulations! You has been successfully authenticated':
              'Congratulations! You has been successfully authenticated',
          'Congratulations! Your email has been successfully updated':
              'Congratulations! Your email has been successfully updated',
          'Congratulations! Your number has been successfully updated':
              'Congratulations! Your number has been successfully updated',
          'You can Connect with': 'You can Connect with',
          'Forgot Password?': 'Forgot Password?',
          'Change Email': 'Change Email',
          'Change Number': 'Change Number',
          'Change Password': 'Change Password',
          'Please wait for a while!': 'Please wait for a while!',
          'Your Measurements are Ready': 'Your Measurements are Ready',
          'Didn’t get the Code? ': 'Didn’t get the Code? ',
          'Don’t have account? ': 'Don’t have account? ',
          'Already have account? ': 'Already have account? ',
          'Start Exploring': 'Start Exploring',
          'Meet Your Stylist': 'Meet Your Stylist',
          'Sign Up': 'Sign Up',
          'Accept': 'Accept',
          'Cancel': 'Cancel',
          '1': '1',
          '2': '2',
          '3': '3',
          'You\'re All Set! Here\'s How to Get Started':
              'You\'re All Set! Here\'s How to Get Started',
          'Try on 3d Model': 'Try on 3d Model',
          'Capture from the Side View': 'Capture from the Side View',
          'For more accurate measurements, take a side view photo in addition to the front-facing one.':
              'For more accurate measurements, take a side view photo in addition to the front-facing one.',
          'Ensure the camera is at your waist height, and your body is fully visible from the side.':
              'Ensure the camera is at your waist height, and your body is fully visible from the side.',
          'Keep the Camera at Eye Level': 'Keep the Camera at Eye Level',
          'Hold your phone at eye level to ensure the AI can accurately detect your body shape and measurements..':
              'Hold your phone at eye level to ensure the AI can accurately detect your body shape and measurements..',
          'Position Yourself Correctly': 'Position Yourself Correctly',
          'Ensure you are facing the camera directly for accurate measurement.':
              'Ensure you are facing the camera directly for accurate measurement.',
          'Stand straight with your feet shoulder-width apart.':
              'Stand straight with your feet shoulder-width apart.',
          'If you are experiencing any issues, please\nlet us know. We will try to solve them as\nsoon as possible.':
              'If you are experiencing any issues, please\nlet us know. We will try to solve them as\nsoon as possible.',
          'Enter your email or phone number to \nreceive password reset instructions':
              'Enter your email or phone number to \nreceive password reset instructions',
          'Create a strong password to secure \nyour account':
              'Create a strong password to secure \nyour account',
          'Enter the one-time password sent to\nyour email to proceed.':
              'Enter the one-time password sent to\nyour email to proceed.',
          'Enter the one-time password sent to\nyour phone number to proceed.':
              'Enter the one-time password sent to\nyour phone number to proceed.',
          'To take pictures and detect your face':
              'To take pictures and detect your face',
          'Fashionfy would like to access the camera':
              'Fashionfy would like to access the camera',
        },
        "fr_FR": {
          "(App Name) is at the forefront of AI-driven e-commerce innovation. Our mission is to revolutionize online shopping by integrating advanced technology like 3D product visualization, AI-powered recommendations, and augmented reality.\n\nWhat Sets Us Apart?\n• AI Precision: Tailored suggestions based on your unique preferences and measurements.\n• Interactive Shopping: Engage with realistic 3D models and virtual dressing rooms.\n• Real-Time Experience: Always accurate, always live—stay informed with real-time product updates.\n\nOur Vision:\u2028We believe in blending technology with user-centric design to create intuitive, immersive shopping experiences that are enjoyable and effective.\nJoin Us on this journey to redefine the future of e-commerce!":
              "(Nom de l'application) est à la pointe de l’innovation du commerce électronique basé sur l’IA. Notre mission est de révolutionner le shopping en ligne en intégrant des technologies avancées comme la visualisation 3D des produits, les recommandations pilotées par l’IA et la réalité augmentée.\n\nCe qui nous distingue :\n• Précision IA : Suggestions personnalisées selon vos préférences et vos mesures uniques.\n• Shopping interactif : Interagissez avec des modèles 3D réalistes et des cabines d’essayage virtuelles.\n• Expérience en temps réel : Toujours précis, toujours en direct — restez informé grâce aux mises à jour produits en temps réel.\n\nNotre vision :\u2028Nous croyons en l’alliance de la technologie et d’un design centré sur l’utilisateur pour offrir des expériences d’achat intuitives et immersives.\nRejoignez-nous pour redéfinir l’avenir du commerce électronique !",
          "About Us": "À propos de nous",
          "Privacy Policy": "Politique de confidentialité",
          "Terms and conditions": "Conditions générales",
          "Continue": "Continuer",
          "Save Changes": "Enregistrer les modifications",
          "Account Settings": "Paramètres du compte",
          "Save": "Enregistrer",
          "Settings": "Paramètres",
          "Oliver": "Oliver",
          "Nike": "Nike",
          "Notifications": "Notifications",
          "Reset Password": "Réinitialiser le mot de passe",
          "Please replace the respective Widget here":
              "Veuillez remplacer le widget correspondant ici",
          "Sound": "Son",
          "More": "Plus",
          "Remove": "Supprimer",
          "Items": "Articles",
          "Logout": "Déconnexion",
          "Your Style Favorites in One Place":
              "Vos styles favoris à un seul endroit",
          "Air Force 1 Jester XX Black Sonic":
              "Air Force 1 Jester XX Noir Sonic",
          "Air Force 1 Shadow Beige Pale Ivory":
              "Air Force 1 Shadow Beige Ivoire Pâle",
          "Upcoming Party": "Fête à venir",
          "121 items": "121 articles",
          "Choose an Option": "Choisissez une option",
          "Tour to Dubai": "Voyage à Dubaï",
          "Add a profile": "Ajouter un profil",
          "Language": "Langue",
          "Select Language": "Sélectionner la langue",
          "Profile Options": "Options de profil",
          "Choose a profile to continue": "Choisissez un profil pour continuer",
          "Nike -098": "Nike -098",
          "Sunglasses": "Lunettes de soleil",
          "Style & Try-On": "Style & Essayage",
          "Men": "Hommes",
          "Women": "Femmes",
          "Kids": "Enfants",
          "Add to Favourites": "Ajouter aux favoris",
          "\$85.5": "85,50 \$",
          "\$96": "96,00 \$",
          "\$115": "115,00 \$",
          "Home": "Accueil",
          "Shoes": "Chaussures",
          "25 products found": "25 produits trouvés",
          "Search": "Rechercher",
          "Search product": "Rechercher un produit",
          "Favourites": "Favoris",
          "Profile": "Profil",
          "Measure": "Mesurer",
          "Theme": "Thème",
          "Emotes": "Émoticônes",
          "Mode": "Mode",
          "AR": "RA",
          "Resend": "Renvoyer",
          "Verify": "Vérifier",
          "Analyzing": "Analyse en cours",
          "Analyzed": "Analysé",
          "English (United Kingdom)": "Anglais (Royaume-Uni)",
          "English (United States)": "Anglais (États-Unis)",
          "Hindi": "Hindi",
          "Spanish": "Espagnol",
          "French": "Français",
          "Name": "Nom",
          "Gender": "Genre",
          "Weight": "Poids",
          "Body Type": "Type de corps",
          "Age": "Âge",
          "Measurements": "Mesures",
          "Height": "Taille",
          "Chest": "Poitrine",
          "Bicep": "Biceps",
          "Waist": "Tour de taille",
          "Hip": "Hanche",
          "170.00 cm": "170,00 cm",
          "96.00 cm": "96,00 cm",
          "33.00 cm": "33,00 cm",
          "99.00 cm": "99,00 cm",
          "Review Your Measured Data": "Vérifiez vos données mesurées",
          "Verification": "Vérification",
          "Next": "Suivant",
          "Account Recovery": "Récupération de compte",
          "Phone / Email": "Téléphone / Email",
          "Send code via oli***r@gmail.com":
              "Envoyer le code à oli***r@gmail.com",
          "Send code via +966 5* **** ***":
              "Envoyer le code à +966 5* **** ***",
          "Set New Password": "Définir un nouveau mot de passe",
          "oliver@gmail.com": "oliver@gmail.com",
          "New Email": "Nouvel email",
          "New Number": "Nouveau numéro",
          "New Password": "Nouveau mot de passe",
          "Old Password": "Ancien mot de passe",
          "Oliver Wyman": "Oliver Wyman",
          "Confirm New Password": "Confirmer le nouveau mot de passe",
          "Confirm Password": "Confirmer le mot de passe",
          "Confirm New Email": "Confirmer le nouvel email",
          "Confirm New Number": "Confirmer le nouveau numéro",
          "Update your email address.": "Mettez à jour votre adresse email.",
          "Update your phone number.":
              "Mettez à jour votre numéro de téléphone.",
          "Update Your Profile Information":
              "Mettez à jour les informations de votre profil",
          "Edit Profile": "Modifier le profil",
          "Title": "Titre",
          "Submit": "Soumettre",
          "Help": "Aide",
          "Cap": "Casquette",
          "Buy": "Acheter",
          "Explain the problem": "Expliquez le problème",
          "Login to explore AI styling.":
              "Connectez-vous pour explorer le style basé sur l'IA.",
          "Add your query here": "Ajoutez votre question ici",
          "How It Works": "Comment ça fonctionne",
          "Password": "Mot de passe",
          "Log in": "Se connecter",
          "Email": "E-mail",
          "Phone": "Téléphone",
          "Create Profile": "Créer un profil",
          "Set Up Your Profile": "Configurer votre profil",
          "Enter details for personalized picks":
              "Saisissez les détails pour des suggestions personnalisées",
          "Success": "Succès",
          "By continuing you accept our": "En continuant, vous acceptez nos",
          "Register to start your personalized shopping journey":
              "Inscrivez-vous pour commencer votre expérience d'achat personnalisée",
          "Congratulations! Password has been successfully updated":
              "Félicitations ! Le mot de passe a été mis à jour avec succès",
          "Congratulations! You has been \nsuccessfully created":
              "Félicitations ! Votre compte a été créé avec succès",
          "Congratulations! Your profile has been successfully created":
              "Félicitations ! Votre profil a été créé avec succès",
          "Congratulations! You has been successfully authenticated":
              "Félicitations ! Vous avez été authentifié avec succès",
          "Congratulations! Your email has been successfully updated":
              "Félicitations ! Votre e-mail a été mis à jour avec succès",
          "Congratulations! Your number has been successfully updated":
              "Félicitations ! Votre numéro a été mis à jour avec succès",
          "You can Connect with": "Vous pouvez vous connecter avec",
          "Forgot Password?": "Mot de passe oublié ?",
          "Change Email": "Changer l'e-mail",
          "Change Number": "Changer le numéro",
          "Change Password": "Changer le mot de passe",
          "Please wait for a while!": "Veuillez patienter un moment !",
          "Your Measurements are Ready": "Vos mesures sont prêtes",
          "Didn’t get the Code? ": "Vous n'avez pas reçu le code ? ",
          "Don’t have account? ": "Vous n'avez pas de compte ? ",
          "Already have account? ": "Vous avez déjà un compte ? ",
          "Start Exploring": "Commencer à explorer",
          "Meet Your Stylist": "Rencontrez votre styliste",
          "Sign Up": "S'inscrire",
          "Accept": "Accepter",
          "Cancel": "Annuler",
          "1": "1",
          "2": "2",
          "3": "3",
          "You're All Set! Here's How to Get Started":
              "Tout est prêt ! Voici comment commencer",
          "Try on 3d Model": "Essayez sur un modèle 3D",
          "Capture from the Side View": "Capturez depuis la vue latérale",
          "For more accurate measurements, take a side view photo in addition to the front-facing one.":
              "Pour des mesures plus précises, prenez une photo de côté en plus de celle de face.",
          "Ensure the camera is at your waist height, and your body is fully visible from the side.":
              "Assurez-vous que la caméra est à la hauteur de votre taille et que votre corps est entièrement visible de côté.",
          "Keep the Camera at Eye Level": "Gardez la caméra au niveau des yeux",
          "Hold your phone at eye level to ensure the AI can accurately detect your body shape and measurements..":
              "Tenez votre téléphone au niveau des yeux pour que l'IA puisse détecter avec précision votre morphologie et vos mesures.",
          "Position Yourself Correctly": "Positionnez-vous correctement",
          "Ensure you are facing the camera directly for accurate measurement.":
              "Assurez-vous de faire face à la caméra pour une mesure précise.",
          "Stand straight with your feet shoulder-width apart.":
              "Tenez-vous droit, les pieds écartés à la largeur des épaules.",
          "If you are experiencing any issues, please\nlet us know. We will try to solve them as\nsoon as possible.":
              "Si vous rencontrez des problèmes, veuillez\nnous en informer. Nous essaierons de les résoudre\ndès que possible.",
          "Enter your email or phone number to \nreceive password reset instructions":
              "Saisissez votre e-mail ou numéro de téléphone pour\nrecevoir les instructions de réinitialisation du mot de passe",
          "Create a strong password to secure \nyour account":
              "Créez un mot de passe fort pour sécuriser\nvotre compte",
          "Enter the one-time password sent to\nyour email to proceed.":
              "Entrez le mot de passe à usage unique envoyé\nà votre e-mail pour continuer.",
          "Enter the one-time password sent to\nyour phone number to proceed.":
              "Entrez le mot de passe à usage unique envoyé\nà votre numéro de téléphone pour continuer.",
          "To take pictures and detect your face":
              "Pour prendre des photos et détecter votre visage",
          "Fashionfy would like to access the camera":
              "Fashionfy souhaite accéder à la caméra"
        },
        "ar_AR": {
          "(App Name) is at the forefront of AI-driven e-commerce innovation. Our mission is to revolutionize online shopping by integrating advanced technology like 3D product visualization, AI-powered recommendations, and augmented reality.\n\nWhat Sets Us Apart?\n• AI Precision: Tailored suggestions based on your unique preferences and measurements.\n• Interactive Shopping: Engage with realistic 3D models and virtual dressing rooms.\n• Real-Time Experience: Always accurate, always live—stay informed with real-time product updates.\n\nOur Vision:\u2028We believe in blending technology with user-centric design to create intuitive, immersive shopping experiences that are enjoyable and effective.\nJoin Us on this journey to redefine the future of e-commerce!":
              "(اسم التطبيق) في طليعة الابتكار في التجارة الإلكترونية المدفوعة بالذكاء الاصطناعي. مهمتنا هي ثورة في التسوق عبر الإنترنت من خلال دمج التكنولوجيا المتقدمة مثل عرض المنتجات ثلاثية الأبعاد، والتوصيات المدعومة بالذكاء الاصطناعي، والواقع المعزز.\n\nما الذي يميزنا؟\n• دقة الذكاء الاصطناعي: اقتراحات مخصصة بناءً على تفضيلاتك وقياساتك الفريدة.\n• تسوق تفاعلي: تفاعل مع نماذج ثلاثية الأبعاد واقعية وغرف قياس افتراضية.\n• تجربة مباشرة: دائمًا دقيقة، دائمًا مباشرة — ابقَ مطلعًا على تحديثات المنتجات في الوقت الفعلي.\n\nرؤيتنا:\u2028نؤمن بدمج التكنولوجيا مع التصميم الموجه للمستخدم لإنشاء تجارب تسوق غامرة وبديهية وفعالة.\nانضم إلينا في هذه الرحلة لإعادة تعريف مستقبل التجارة الإلكترونية!",
          "About Us": "معلومات عنا",
          "Privacy Policy": "سياسة الخصوصية",
          "Terms and conditions": "الشروط والأحكام",
          "Continue": "متابعة",
          "Save Changes": "حفظ التغييرات",
          "Account Settings": "إعدادات الحساب",
          "Save": "حفظ",
          "Settings": "الإعدادات",
          "Oliver": "أوليفر",
          "Nike": "نايكي",
          "Notifications": "الإشعارات",
          "Reset Password": "إعادة تعيين كلمة المرور",
          "Please replace the respective Widget here":
              "يرجى استبدال الأداة المناسبة هنا",
          "Sound": "الصوت",
          "More": "المزيد",
          "Remove": "إزالة",
          "Items": "العناصر",
          "Logout": "تسجيل الخروج",
          "Your Style Favorites in One Place":
              "المفضلات الخاصة بك في مكان واحد",
          "Air Force 1 Jester XX Black Sonic": "إير فورس 1 جيستر XX بلاك سونيك",
          "Air Force 1 Shadow Beige Pale Ivory":
              "إير فورس 1 شادو بيج عاجي فاتح",
          "Upcoming Party": "الحفلة القادمة",
          "121 items": "١٢١ عنصرًا",
          "Choose an Option": "اختر خيارًا",
          "Tour to Dubai": "رحلة إلى دبي",
          "Add a profile": "إضافة ملف شخصي",
          "Language": "اللغة",
          "Select Language": "اختر اللغة",
          "Profile Options": "خيارات الملف الشخصي",
          "Choose a profile to continue": "اختر ملفًا شخصيًا للمتابعة",
          "Nike -098": "نايكي -٠٩٨",
          "Sunglasses": "نظارات شمسية",
          "Style & Try-On": "الأسلوب والتجريب",
          "Men": "رجال",
          "Women": "نساء",
          "Kids": "أطفال",
          "Add to Favourites": "إضافة إلى المفضلة",
          "\$85.5": "٨٥٫٥٠ دولار",
          "\$96": "٩٦٫٠٠ دولار",
          "\$115": "١١٥٫٠٠ دولار",
          "Home": "الرئيسية",
          "Shoes": "أحذية",
          "25 products found": "تم العثور على ٢٥ منتجًا",
          "Search": "بحث",
          "Search product": "ابحث عن منتج",
          "Favourites": "المفضلة",
          "Profile": "الملف الشخصي",
          "Measure": "قياس",
          "Theme": "السمة",
          "Emotes": "الرموز التعبيرية",
          "Mode": "الوضع",
          "AR": "الواقع المعزز",
          "Resend": "إعادة الإرسال",
          "Verify": "تحقق",
          "Analyzing": "جارٍ التحليل",
          "Analyzed": "تم التحليل",
          "English (United Kingdom)": "الإنجليزية (المملكة المتحدة)",
          "English (United States)": "الإنجليزية (الولايات المتحدة)",
          "Hindi": "الهندية",
          "Spanish": "الإسبانية",
          "French": "الفرنسية",
          "Name": "الاسم",
          "Gender": "الجنس",
          "Weight": "الوزن",
          "Body Type": "نوع الجسم",
          "Age": "العمر",
          "Measurements": "القياسات",
          "Height": "الطول",
          "Chest": "الصدر",
          "Bicep": "عضلة الذراع",
          "Waist": "الخصر",
          "Hip": "الورك",
          "170.00 cm": "١٧٠٫٠٠ سم",
          "96.00 cm": "٩٦٫٠٠ سم",
          "33.00 cm": "٣٣٫٠٠ سم",
          "99.00 cm": "٩٩٫٠٠ سم",
          "Review Your Measured Data": "راجع بيانات قياساتك",
          "Verification": "التحقق",
          "Next": "التالي",
          "Account Recovery": "استعادة الحساب",
          "Phone / Email": "الهاتف / البريد الإلكتروني",
          "Send code via oli***r@gmail.com":
              "إرسال الرمز إلى oli***r@gmail.com",
          "Send code via +966 5* **** ***": "إرسال الرمز إلى +966 5* **** ***",
          "Set New Password": "تعيين كلمة مرور جديدة",
          "oliver@gmail.com": "oliver@gmail.com",
          "New Email": "البريد الإلكتروني الجديد",
          "New Number": "الرقم الجديد",
          "New Password": "كلمة المرور الجديدة",
          "Old Password": "كلمة المرور القديمة",
          "Oliver Wyman": "أوليفر وايمان",
          "Confirm New Password": "تأكيد كلمة المرور الجديدة",
          "Confirm Password": "تأكيد كلمة المرور",
          "Confirm New Email": "تأكيد البريد الإلكتروني الجديد",
          "Confirm New Number": "تأكيد الرقم الجديد",
          "Update your email address.": "تحديث عنوان بريدك الإلكتروني.",
          "Update your phone number.": "تحديث رقم هاتفك.",
          "Update Your Profile Information": "تحديث معلومات ملفك الشخصي",
          "Edit Profile": "تعديل الملف الشخصي",
          "Title": "العنوان",
          "Submit": "إرسال",
          "Help": "مساعدة",
          "Cap": "قبعة",
          "Buy": "شراء",
          "Explain the problem": "اشرح المشكلة",
          "Login to explore AI styling.":
              "سجّل الدخول لاستكشاف تنسيق الذكاء الاصطناعي.",
          "Add your query here": "أضف سؤالك هنا",
          "How It Works": "كيف يعمل",
          "Password": "كلمة المرور",
          "Log in": "تسجيل الدخول",
          "Email": "البريد الإلكتروني",
          "Phone": "رقم الهاتف",
          "Create Profile": "إنشاء ملف شخصي",
          "Set Up Your Profile": "إعداد ملفك الشخصي",
          "Enter details for personalized picks":
              "أدخل التفاصيل للحصول على اختيارات مخصصة",
          "Success": "نجاح",
          "By continuing you accept our": "بالمتابعة، فإنك تقبل",
          "Register to start your personalized shopping journey":
              "سجّل لبدء تجربة التسوق المخصصة الخاصة بك",
          "Congratulations! Password has been successfully updated":
              "تهانينا! تم تحديث كلمة المرور بنجاح",
          "Congratulations! You has been \nsuccessfully created":
              "تهانينا! تم إنشاء حسابك بنجاح",
          "Congratulations! Your profile has been successfully created":
              "تهانينا! تم إنشاء ملفك الشخصي بنجاح",
          "Congratulations! You has been successfully authenticated":
              "تهانينا! تم التحقق من هويتك بنجاح",
          "Congratulations! Your email has been successfully updated":
              "تهانينا! تم تحديث بريدك الإلكتروني بنجاح",
          "Congratulations! Your number has been successfully updated":
              "تهانينا! تم تحديث رقمك بنجاح",
          "You can Connect with": "يمكنك الاتصال بـ",
          "Forgot Password?": "هل نسيت كلمة المرور؟",
          "Change Email": "تغيير البريد الإلكتروني",
          "Change Number": "تغيير الرقم",
          "Change Password": "تغيير كلمة المرور",
          "Please wait for a while!": "يرجى الانتظار قليلاً!",
          "Your Measurements are Ready": "قياساتك جاهزة",
          "Didn’t get the Code? ": "لم يصلك الرمز؟ ",
          "Don’t have account? ": "ليس لديك حساب؟ ",
          "Already have account? ": "هل لديك حساب بالفعل؟ ",
          "Start Exploring": "ابدأ الاستكشاف",
          "Meet Your Stylist": "قابل مصمم الأزياء الخاص بك",
          "Sign Up": "سجّل",
          "Accept": "قبول",
          "Cancel": "إلغاء",
          "1": "١",
          "2": "٢",
          "3": "٣",
          "You're All Set! Here's How to Get Started":
              "كل شيء جاهز! إليك كيفية البدء",
          "Try on 3d Model": "جرب على نموذج ثلاثي الأبعاد",
          "Capture from the Side View": "التقط صورة من الجانب",
          "For more accurate measurements, take a side view photo in addition to the front-facing one.":
              "للحصول على قياسات أدق، التقط صورة جانبية بالإضافة إلى الصورة الأمامية.",
          "Ensure the camera is at your waist height, and your body is fully visible from the side.":
              "تأكد من أن الكاميرا في مستوى خصرك وأن جسمك مرئي بالكامل من الجانب.",
          "Keep the Camera at Eye Level": "أبقِ الكاميرا في مستوى العين",
          "Hold your phone at eye level to ensure the AI can accurately detect your body shape and measurements..":
              "أمسك هاتفك في مستوى العين ليتمكن الذكاء الاصطناعي من تحديد شكل جسمك وقياساتك بدقة.",
          "Position Yourself Correctly": "ضع نفسك في الموضع الصحيح",
          "Ensure you are facing the camera directly for accurate measurement.":
              "تأكد من أنك تواجه الكاميرا مباشرة للحصول على قياسات دقيقة.",
          "Stand straight with your feet shoulder-width apart.":
              "قف بشكل مستقيم وابقِ قدميك بعرض الكتفين.",
          "If you are experiencing any issues, please\nlet us know. We will try to solve them as\nsoon as possible.":
              "إذا كنت تواجه أي مشاكل، يرجى\nإبلاغنا. سنحاول حلها\nفي أقرب وقت ممكن.",
          "Enter your email or phone number to \nreceive password reset instructions":
              "أدخل بريدك الإلكتروني أو رقم هاتفك\nلتلقي تعليمات إعادة تعيين كلمة المرور",
          "Create a strong password to secure \nyour account":
              "أنشئ كلمة مرور قوية لتأمين حسابك",
          "Enter the one-time password sent to\nyour email to proceed.":
              "أدخل رمز التحقق المرسل إلى بريدك الإلكتروني للمتابعة.",
          "Enter the one-time password sent to\nyour phone number to proceed.":
              "أدخل رمز التحقق المرسل إلى رقم هاتفك للمتابعة.",
          "To take pictures and detect your face":
              "لالتقاط الصور والتعرف على وجهك",
          "Fashionfy would like to access the camera":
              "تطبيق Fashionfy يطلب الوصول إلى الكاميرا"
        }
      };
}
